2022.10.29 21:15:29;No quedan reintentos disponibles para recuperarse de un error.
<class 'requests.exceptions.ConnectionError'>: 
2022.10.29 21:21:19;No quedan reintentos disponibles para recuperarse de un error.
<class 'requests.exceptions.ConnectionError'>: 
2022.10.29 21:22:16;No quedan reintentos disponibles para recuperarse de un error.Y se recibió: <class 'requests.exceptions.ConnectionError'>: 
2022.10.29 21:22:49;No quedan reintentos disponibles para recuperarse de un error.
Y se recibió:
<class 'requests.exceptions.ConnectionError'>: 
2022.10.29 21:28:59;No quedan reintentos disponibles para recuperarse de un error.
Y se recibió:
: 
2022.10.29 21:33:20;No quedan reintentos disponibles para recuperarse de un error.
Y se recibió:
Mocked: RequestException(): Mocked: RequestException()
2022.10.29 21:35:14;No quedan reintentos disponibles para recuperarse de un error.
Y se recibió:
Mocked: RequestException()
2022.10.29 21:35:36;No quedan reintentos disponibles para recuperarse de un error.
Y se recibió:
MockedRequestException()
