2022.10.26 16:41:39;-----------------------------------------------
2022.10.26 16:41:39;--------------- Nueva ejecución ---------------
2022.10.26 16:41:39;-----------------------------------------------
2022.10.26 16:41:39;Partiendo una ejecución nueva con 0.2 minutos de espera entre búsquedas...
2022.10.26 16:42:37;      full - Albacete - Alemania - El horario de atención al cliente está completo para los próximos días. Inténtelo más tarde.
2022.10.26 16:43:27;      full - Albacete - Argentina - El horario de atención al cliente está completo para los próximos días. Inténtelo más tarde.
2022.10.26 16:44:43;     error - Albacete - Austria - Por favor, inténtalo más tarde
2022.10.26 16:46:12;      full - Albacete - Austria - El horario de atención al cliente está completo para los próximos días. Inténtelo más tarde.
2022.10.26 16:46:57;      full - Albacete - Bolivia - El horario de atención al cliente está completo para los próximos días. Inténtelo más tarde.
2022.10.26 16:48:12;      full - Albacete - Brasil - El horario de atención al cliente está completo para los próximos días. Inténtelo más tarde.
2022.10.26 16:49:11;   antibot - Albacete - Chile - Estamos recibiendo un número muy elevado de accesos que no nos permiten procesar tu petición. Por favor, inténtalo de nuevo pasados unos minutos.
2022.10.26 16:49:48;      full - Albacete - Chile - El horario de atención al cliente está completo para los próximos días. Inténtelo más tarde.
2022.10.26 16:51:03;      full - Albacete - Colombia - El horario de atención al cliente está completo para los próximos días. Inténtelo más tarde.
2022.10.26 16:51:45;      full - Albacete - Costa Rica - El horario de atención al cliente está completo para los próximos días. Inténtelo más tarde.
2022.10.26 16:52:24;      full - Albacete - Croacia - El horario de atención al cliente está completo para los próximos días. Inténtelo más tarde.
2022.10.26 16:53:39;     error - Albacete - Dinamarca - Por favor, inténtalo más tarde
2022.10.26 16:54:54;      full - Albacete - Dinamarca - El horario de atención al cliente está completo para los próximos días. Inténtelo más tarde.
2022.10.26 16:55:36;      full - Albacete - Ecuador - El horario de atención al cliente está completo para los próximos días. Inténtelo más tarde.
2022.10.26 16:56:23;      full - Albacete - El Salvador - El horario de atención al cliente está completo para los próximos días. Inténtelo más tarde.
2022.10.26 16:57:03;      full - Albacete - Eslovenia - El horario de atención al cliente está completo para los próximos días. Inténtelo más tarde.
2022.10.26 16:57:49;      full - Albacete - Francia - El horario de atención al cliente está completo para los próximos días. Inténtelo más tarde.
2022.10.26 16:58:45;      full - Albacete - Ucrania - El horario de atención al cliente está completo para los próximos días. Inténtelo más tarde.
2022.10.26 16:59:46;      full - Albacete - Uruguay - El horario de atención al cliente está completo para los próximos días. Inténtelo más tarde.
2022.10.26 17:00:28;      full - Alicante/Alacant - Alemania - El horario de atención al cliente está completo para los próximos días. Inténtelo más tarde.
2022.10.26 17:01:37;      full - Alicante/Alacant - Argentina - El horario de atención al cliente está completo para los próximos días. Inténtelo más tarde.
2022.10.26 17:03:42;        ok - Alicante/Alacant - Austria - Por favor, inténtalo más tarde
2022.10.26 17:03:42;*******   HAY HORARIOS DISPONIBLES - VER ARRIBA   *******
2022.10.26 17:06:44;        ok - Alicante/Alacant - Bolivia - Por favor, inténtalo más tarde
2022.10.26 17:06:44;*******   HAY HORARIOS DISPONIBLES - VER ARRIBA   *******
2022.10.26 17:09:55;response no tiene un json válido. Detalles en log de debug
2022.10.26 17:09:55;Uncaught exception: 
Traceback (most recent call last):
  File "C:\git\WaaS_Alert\ScheduleLookup.py", line 85, in <module>
    many_lookups()
  File "C:\git\WaaS_Alert\ScheduleLookup.py", line 80, in many_lookups
    schedule_lookup()
  File "C:\git\WaaS_Alert\ScheduleLookup.py", line 62, in schedule_lookup
    lookup_status, msg = lookup(office=office, country=country)
  File "C:\git\WaaS_Alert\Lookup.py", line 78, in lookup
    r_json = response_to_json(response=response)
  File "C:\git\WaaS_Alert\Lookup.py", line 39, in response_to_json
    raise e
  File "C:\git\WaaS_Alert\Lookup.py", line 34, in response_to_json
    r_json: dict = json.loads(response.text)
  File "C:\Users\rober\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\rober\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\rober\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022.10.26 17:15:20;     error - <mocked> - <mocked> - Authorization failed
2022.10.26 18:04:52;-----------------------------------------------
2022.10.26 18:04:52;--------------- Nueva ejecución ---------------
2022.10.26 18:04:52;-----------------------------------------------
2022.10.26 18:04:52;Partiendo una ejecución nueva con 0.2 minutos de espera entre búsquedas...
2022.10.26 18:05:58;      full - Albacete - Alemania - El horario de atención al cliente está completo para los próximos días. Inténtelo más tarde.
2022.10.26 18:09:09;504: Timeout
2022.10.26 18:09:09;Uncaught exception: 
Traceback (most recent call last):
  File "C:\git\WaaS_Alert\ScheduleLookup.py", line 85, in <module>
    many_lookups()
  File "C:\git\WaaS_Alert\ScheduleLookup.py", line 80, in many_lookups
    schedule_lookup()
  File "C:\git\WaaS_Alert\ScheduleLookup.py", line 62, in schedule_lookup
    lookup_status, msg = lookup(office=office, country=country)
  File "C:\git\WaaS_Alert\Lookup.py", line 88, in lookup
    lookup_status = get_lookup_status(r_json=r_json)
  File "C:\git\WaaS_Alert\Lookup.py", line 110, in get_lookup_status
    raise NewMessageInResponse(msg)
Lookup.NewMessageInResponse: <html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx</center>
</body>
</html>

2022.10.26 18:22:39;504: Timeout
2022.10.26 18:23:39;504: Timeout
2022.10.26 18:23:39;   timeout - <mocked> - <mocked> - <html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx</center>
</body>
</html>

